//
//  DetailRssInterfaces.swift
//  rssNasa
//
//  Created by Pablo Vélez  on 29/11/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum DetailRssNavigationOption {
}

protocol DetailRssWireframeInterface: WireframeInterface {
    func navigate(to option: DetailRssNavigationOption)
}

protocol DetailRssViewInterface: ViewInterface {
}

protocol DetailRssPresenterInterface: PresenterInterface {
}

protocol DetailRssInteractorInterface: InteractorInterface {
}
