//
//  DetailRssWireframe.swift
//  rssNasa
//
//  Created by Pablo Vélez  on 29/11/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailRssWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "DetailRss", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: DetailRssViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = DetailRssInteractor()
        let presenter = DetailRssPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailRssWireframe: DetailRssWireframeInterface {

    func navigate(to option: DetailRssNavigationOption) {
    }
}
