//
//  DetailRssViewController.swift
//  rssNasa
//
//  Created by Pablo Vélez  on 29/11/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailRssViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: DetailRssPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension DetailRssViewController: DetailRssViewInterface {
}
