//
//  DetailRssPresenter.swift
//  rssNasa
//
//  Created by Pablo Vélez  on 29/11/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailRssPresenter {

    // MARK: - Private properties -

    private unowned var _view: DetailRssViewInterface
    private var _interactor: DetailRssInteractorInterface
    private var _wireframe: DetailRssWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: DetailRssWireframeInterface, view: DetailRssViewInterface, interactor: DetailRssInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension DetailRssPresenter: DetailRssPresenterInterface {
}
