//
//  DetailRssInteractor.swift
//  rssNasa
//
//  Created by Pablo Vélez  on 29/11/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailRssInteractor {
}

// MARK: - Extensions -

extension DetailRssInteractor: DetailRssInteractorInterface {
}
