//
//  ListRssViewController.swift
//  rssNasa
//
//  Created by Pablo Vélez  on 27/11/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ListRssViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: ListRssPresenterInterface!
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
        tableView.dataSource = self
        tableView.delegate = self
    }
	
}

// MARK: - Extensions -

extension ListRssViewController: ListRssViewInterface {
    func reloadData() {
        self.tableView.reloadData()
    }
    
}

extension ListRssViewController: UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return presenter.numberOfSections()
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.numberOfItems(in: section)
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        //Metodo encargado de configurar la celda
        let cell = tableView.dequeueReusableCell(withIdentifier: "ListRSSCell", for: indexPath) as! ListRSSCell
        let item = presenter.item(at: indexPath)
        cell.configure(with: item)
            
        _handleRowColor(cell: cell, indexPath: indexPath, tableView: tableView)
        
        return cell
    }
    
    private func _handleRowColor(cell: UITableViewCell, indexPath: IndexPath, tableView: UITableView) {
        if((indexPath.row % 2) == 0){
            cell.backgroundColor = .white
        } else {
            //Color gris tenue
            cell.backgroundColor = UIColor(red:0.93, green:0.93, blue:0.93, alpha:1.0)
        }
    }
    
}

extension ListRssViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        presenter.didSelectItem(at: indexPath)
    }
}

