//
//  ListRssInterfaces.swift
//  rssNasa
//
//  Created by Pablo Vélez  on 27/11/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

enum ListRssNavigationOption {
}

protocol ListRssWireframeInterface: WireframeInterface {
    func navigate(to option: ListRssNavigationOption)
}

protocol ListRssViewInterface: ViewInterface {
    func reloadData()
}

protocol ListRssPresenterInterface: PresenterInterface {
    func startFetchData()
    
    func numberOfSections() -> Int
    func numberOfItems(in section: Int) -> Int
    func item(at indexPath: IndexPath) -> Item
    func didSelectItem(at indexPath: IndexPath)
}

protocol ListRssInteractorInterface: InteractorInterface {
    @discardableResult
    func getListRSS(_ completion: @escaping ListRSSCompletionBlock) -> DataRequest
}
