//
//  ListRssWireframe.swift
//  rssNasa
//
//  Created by Pablo Vélez  on 27/11/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ListRssWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "ListRss", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: ListRssViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = ListRssInteractor()
        let presenter = ListRssPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ListRssWireframe: ListRssWireframeInterface {

    func navigate(to option: ListRssNavigationOption) {
    }
}
