//
//  ListRssPresenter.swift
//  rssNasa
//
//  Created by Pablo Vélez  on 27/11/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ListRssPresenter {

    // MARK: - Private properties -

    private unowned var _view: ListRssViewInterface
    private var _interactor: ListRssInteractorInterface
    private var _wireframe: ListRssWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: ListRssWireframeInterface, view: ListRssViewInterface, interactor: ListRssInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension ListRssPresenter: ListRssPresenterInterface {
}
