//
//  ListRssInteractor.swift
//  rssNasa
//
//  Created by Pablo Vélez  on 27/11/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ListRssInteractor {
}

// MARK: - Extensions -

extension ListRssInteractor: ListRssInteractorInterface {
}
